apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: kq19o1i34-nodejs
  janus-idp.io/tekton: kq19o1i34-nodejs
  backstage.io/kubernetes-id: kq19o1i34-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: kq19o1i34-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
