apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: kq19o1i34-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kq19o1i34-nodejs 
  name: kq19o1i34-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: kq19o1i34-nodejs 
